### ISSUE TITLE
VideoKitSampleTRIAL always crashes Xcode 11.3.1 + iOS 13.3.1

### ISSUE THREAD

**Issue by nekot** [tnadus/iOS-VideoKit-TRIAL#7]
When I run VideoKitSampleTRIAL on iPhone 11 Pro Max(iOS 13.3.1) built with Xcode 11.3.1, app always crashes.

VideoKitSampleTRIAL[65358:15319056] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Unable to parse constraint format: 
Unable to interpret '|' character, because the related view doesn't have a superview 
H:|-62-[_viewCenteredOnBar]-62-|

**Comment by tnadus** [comment]
Hi nekot, a new version is on its way, hopefully it will be released soon...
